# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Informacion del sitio
site_name: Documentación Azure Portal FFDS-SDS Tenant
site_url: https://mydomain.org/mysite
site_author: Jsmartinez
site_description: >-
  Sitio de prueba estatico que contiene documentacion referente a la gestion y gobernanza del portal de Azure para la SDS-FFDS.

# Repositorio
## repo_name: jsmm92/mkdocs-work
##repo_url: https://github.com/jsmm92/mkdocs-work.git

#copyright
copyright: Copyright &copy; 2024 JSMartinez

#Extensions

#Configuration
theme: 
  name: material
  ##custom_dir: overrides
  features:
    - announce.dismiss
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
   ## - navigation.instant
    - navigation.sections
  ##  - navigation.tabs.sticky
  ##  - navigation.tabs
    - navigation.top
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
  ## - toc.follow
  ## - toc.integrate
    - search.suggest
    - search.highlight
    - search.share  
  ## - header.autohide
  ## - navigation.instant.preview
  language: en
  icon:
    logo: material/library-outline
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
     
  palette:
   # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal    
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
 ## font:
   ## text: Ubuntu
   ## code: Ubuntu Mono
  ## favicon: luc.png
  ## logo: luc.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition 
  - pymdownx.superfences:   # Features
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
# Customization
extra:
  homepage: http://127.0.0.1:8000/ ##https://mydomain.org/mysite   
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/.../issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: ""
    - icon: fontawesome/brands/twitter
      link: ""   
#extra_css:
 # - stylesheets/extra.css
# Page Tree
nav:
  - Inicio: 
    - index.md
    - Arquitectura:
      - 1 - Arquitectura modelo Hub And Spoke Azure SDS: arquitectura.md
      - 2 - Management Group, Tenant Root Group y Suscripciones: suscripciones.md
      - 3 - Arquitectura de Red: network.md
    - Gestion de Identidad:
      - 4 - Seguridad Control de Acceso y Gestión de Identidades RBAC: identidad.md
    - Recursos:
      - 5 - Aplicaciones y servicios desplegados en el portal de Azure FFDS: aplicaciones.md
      - 6 - Depuración de Recursos: depuracion.md
    - Billing:
      - 7 - Facturación y Costos: facturacion.md
    - Monitor:
      - 8 - Monitoreo y Registro de actividades e Incidentes: monitoreo.md
    - Gestion de Backup:
      - 9 - Backup y Recuperación de Datos: backup.md
    - Cloud Adoption Framework CAF:
      - 10 - Adopcion de la nube, estrategias y Mejores Prácticas: caf.md
    - Documentacion y herramientas:
      - 11 - Herramientas y Mejores Prácticas: herramientas.md
    
      - Day 10 - Scheduling tasks: 10.md
      - Day 11 - Finding things: 11.md
      - Day 12 - Transferring files: 12.md
      - Day 13 - Users and Groups: 13.md
      - Day 14 - Who has permission?: 14.md
      - Day 15 - Deeper into repositories: 15.md
      - Day 16 - Archiving and compressing: 16.md
      - Day 17 - Build from the source: 17.md
      - Day 18 - Log rotation: 18.md
      - Day 19 - Inodes, symlinks and other shortcuts: 19.md
      - Day 20 - Scripting: 20.md
    - What Now?:
      - Day 21 - What's next?: 21.md